<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * An eBay-defined complex type for specifying monetary amounts.<br><br>A double 
 * value (e.g., 1.00 or 1.0) is meaningful as a monetary amount when accompanied by 
 * a specification of the currency, in which case the value specifies the amount in 
 * that currency. An AmountType expresses both the value (a double) and the 
 * currency.<br><br>The AmountType data type is typically used to specify details 
 * such as prices, fees, costs, and payments. In some cases, a whole number (i.e., 
 * without a period) can be passed or returned as a monetary value. This is 
 * necessary to support certain currencies that are only expressed as whole numbers 
 * (like the Italian Lira and Spanish Peseta).<br><br>Because a double is used to 
 * represent the amount, this also means whole monetary amounts may be returned 
 * with only one 0 after the decimal. For example, a dollar value could be returned 
 * as 1.0 instead of 1.00 in calls like AddItem. For fields of type AmountType, see 
 * the individual topics for specific restrictions beyond this. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/AmountType.html
 *
 */
class AmountType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('AmountType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}	$this->_attributes = array_merge($this->_attributes,
		array(
			'currencyID' =>
			array(
				'name' => 'currencyID',
				'type' => 'CurrencyCodeType',
				'use' => 'required'
			)
		));

	}
}
?>
