<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * This type is deprecated because no calls use it. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/BidderIdType.html
 *
 */
class BidderIdType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('BidderIdType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BidderIdType = new BidderIdType();

?>
