<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated because this type is not used by any call. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/BidderTypeCodeType.html
 *
 * @property string AllBidder
 * @property string HighBidder
 * @property string CustomCode
 */
class BidderTypeCodeType extends EbatNs_FacetType
{
	const CodeType_AllBidder = 'AllBidder';
	const CodeType_HighBidder = 'HighBidder';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('BidderTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_BidderTypeCodeType = new BidderTypeCodeType();

?>
