<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'BuyerProtectionSourceCodeType.php';
require_once 'EbatNs_ComplexType.php';
require_once 'BuyerProtectionCodeType.php';

/**
 * Type defining the <strong>ApplyBuyerProtection</strong> container, whichconsists 
 * of details related to whether or not the item is eligibile for buyer 
 * protectionand which of the buyer protection programs will cover the item. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/BuyerProtectionDetailsType.html
 *
 */
class BuyerProtectionDetailsType extends EbatNs_ComplexType
{
	/**
	 * @var BuyerProtectionSourceCodeType
	 */
	protected $BuyerProtectionSource;
	/**
	 * @var BuyerProtectionCodeType
	 */
	protected $BuyerProtectionStatus;

	/**
	 * @return BuyerProtectionSourceCodeType
	 */
	function getBuyerProtectionSource()
	{
		return $this->BuyerProtectionSource;
	}
	/**
	 * @return void
	 * @param BuyerProtectionSourceCodeType $value 
	 */
	function setBuyerProtectionSource($value)
	{
		$this->BuyerProtectionSource = $value;
	}
	/**
	 * @return BuyerProtectionCodeType
	 */
	function getBuyerProtectionStatus()
	{
		return $this->BuyerProtectionStatus;
	}
	/**
	 * @return void
	 * @param BuyerProtectionCodeType $value 
	 */
	function setBuyerProtectionStatus($value)
	{
		$this->BuyerProtectionStatus = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('BuyerProtectionDetailsType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'BuyerProtectionSource' =>
					array(
						'required' => false,
						'type' => 'BuyerProtectionSourceCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					),
					'BuyerProtectionStatus' =>
					array(
						'required' => false,
						'type' => 'BuyerProtectionCodeType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
