<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated. Use <b>DetailLevelCodeType</b> instead. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CategoryFeatureDetailLevelCodeType.html
 *
 * @property string ReturnAll
 * @property string ReturnFeatureDefinitions
 * @property string CustomCode
 */
class CategoryFeatureDetailLevelCodeType extends EbatNs_FacetType
{
	const CodeType_ReturnAll = 'ReturnAll';
	const CodeType_ReturnFeatureDefinitions = 'ReturnFeatureDefinitions';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CategoryFeatureDetailLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CategoryFeatureDetailLevelCodeType = new CategoryFeatureDetailLevelCodeType();

?>
