<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that defines the seller's preference for allowing Combined 
 * Payment orders that pass on a shipping discount to the buyer. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CombinedPaymentOptionCodeType.html
 *
 * @property string NoCombinedPayment
 * @property string DiscountSpecified
 * @property string SpecifyDiscountLater
 * @property string CustomCode
 */
class CombinedPaymentOptionCodeType extends EbatNs_FacetType
{
	const CodeType_NoCombinedPayment = 'NoCombinedPayment';
	const CodeType_DiscountSpecified = 'DiscountSpecified';
	const CodeType_SpecifyDiscountLater = 'SpecifyDiscountLater';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CombinedPaymentOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CombinedPaymentOptionCodeType = new CombinedPaymentOptionCodeType();

?>
