<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type contains the list of values that can be used by the seller 
 * to setthe number of days after item purchase that an unpaid order can be 
 * combined with one or more other mutual (same buyer and same seller) unpaid 
 * orders into one "Combined Payment" order. Either the buyer or the seller can 
 * initiate the Combined Payment process. Sellers can offer buyers shipping 
 * discounts through Combined Payment orders, and buyers only have to make one 
 * payment for multiple orders as oppposed to a payment for each order. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CombinedPaymentPeriodCodeType.html
 *
 * @property string Days_3
 * @property string Days_5
 * @property string Days_7
 * @property string Days_14
 * @property string Days_30
 * @property string Ineligible
 * @property string CustomCode
 */
class CombinedPaymentPeriodCodeType extends EbatNs_FacetType
{
	const CodeType_Days_3 = 'Days_3';
	const CodeType_Days_5 = 'Days_5';
	const CodeType_Days_7 = 'Days_7';
	const CodeType_Days_14 = 'Days_14';
	const CodeType_Days_30 = 'Days_30';
	const CodeType_Ineligible = 'Ineligible';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CombinedPaymentPeriodCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CombinedPaymentPeriodCodeType = new CombinedPaymentPeriodCodeType();

?>
