<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type list the Feedback ratings that can be left by one eBay user 
 * for another user regarding that user's experience with the another user during 
 * the purchase/checkout flow of an order line item. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/CommentTypeCodeType.html
 *
 * @property string Positive
 * @property string Neutral
 * @property string Negative
 * @property string Withdrawn
 * @property string IndependentlyWithdrawn
 * @property string CustomCode
 */
class CommentTypeCodeType extends EbatNs_FacetType
{
	const CodeType_Positive = 'Positive';
	const CodeType_Neutral = 'Neutral';
	const CodeType_Negative = 'Negative';
	const CodeType_Withdrawn = 'Withdrawn';
	const CodeType_IndependentlyWithdrawn = 'IndependentlyWithdrawn';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('CommentTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_CommentTypeCodeType = new CommentTypeCodeType();

?>
