<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * This type is deprecated as the <b>GetProduct*</b> calls are no longer available. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DataElementSetType.html
 *
 */
class DataElementSetType extends EbatNs_ComplexType
{
	/**
	 * @var string
	 */
	protected $DataElement;
	/**
	 * @var int
	 */
	protected $DataElementID;

	/**
	 * @return string
	 */
	function getDataElement()
	{
		return $this->DataElement;
	}
	/**
	 * @return void
	 * @param string $value 
	 */
	function setDataElement($value)
	{
		$this->DataElement = $value;
	}
	/**
	 * @return int
	 */
	function getDataElementID()
	{
		return $this->DataElementID;
	}
	/**
	 * @return void
	 * @param int $value 
	 */
	function setDataElementID($value)
	{
		$this->DataElementID = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DataElementSetType', 'http://www.w3.org/2001/XMLSchema');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'DataElement' =>
					array(
						'required' => false,
						'type' => 'string',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'DataElementID' =>
					array(
						'required' => false,
						'type' => 'int',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));	$this->_attributes = array_merge($this->_attributes,
		array(
			'attributeSetID' =>
			array(
				'name' => 'attributeSetID',
				'type' => 'int',
				'use' => 'required'
			)
		));

	}
}
?>
