<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated as the call is no longer available. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DateSpecifierCodeType.html
 *
 * @property string M
 * @property string D
 * @property string Y
 * @property string CustomCode
 */
class DateSpecifierCodeType extends EbatNs_FacetType
{
	const CodeType_M = 'M';
	const CodeType_D = 'D';
	const CodeType_Y = 'Y';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DateSpecifierCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DateSpecifierCodeType = new DateSpecifierCodeType();

?>
