<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * The nature of the discount. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DiscountReasonCodeType.html
 *
 * @property string SpecialOffer
 * @property string Promotion
 * @property string CustomCode
 */
class DiscountReasonCodeType extends EbatNs_FacetType
{
	const CodeType_SpecialOffer = 'SpecialOffer';
	const CodeType_Promotion = 'Promotion';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DiscountReasonCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DiscountReasonCodeType = new DiscountReasonCodeType();

?>
