<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that contains the top-level reasons for a buyer or seller to 
 * create acase against one another. These values are specified in 
 * the<b>DisputeReason</b> field of <b>AddDispute</b>, and are returned in the 
 * <b>GetUserDisputes</b> and <b>GetDispute</b> calls.The <b>DisputeReason</b> 
 * value will dictate what <b>DisputeExplanation</b> values that can be 
 * used/returned. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DisputeReasonCodeType.html
 *
 * @property string BuyerHasNotPaid
 * @property string TransactionMutuallyCanceled
 * @property string ItemNotReceived
 * @property string SignificantlyNotAsDescribed
 * @property string NoRefund
 * @property string ReturnPolicyUnpaidItem
 * @property string CustomCode
 */
class DisputeReasonCodeType extends EbatNs_FacetType
{
	const CodeType_BuyerHasNotPaid = 'BuyerHasNotPaid';
	const CodeType_TransactionMutuallyCanceled = 'TransactionMutuallyCanceled';
	const CodeType_ItemNotReceived = 'ItemNotReceived';
	const CodeType_SignificantlyNotAsDescribed = 'SignificantlyNotAsDescribed';
	const CodeType_NoRefund = 'NoRefund';
	const CodeType_ReturnPolicyUnpaidItem = 'ReturnPolicyUnpaidItem';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DisputeReasonCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_DisputeReasonCodeType = new DisputeReasonCodeType();

?>
