<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Contains a seller's cut off time preferences for same day handling for item 
 * shipping. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/DispatchCutoffTimePreferencesType.html
 *
 */
class DispatchCutoffTimePreferencesType extends EbatNs_ComplexType
{
	/**
	 * @var time
	 */
	protected $CutoffTime;

	/**
	 * @return time
	 */
	function getCutoffTime()
	{
		return $this->CutoffTime;
	}
	/**
	 * @return void
	 * @param time $value 
	 */
	function setCutoffTime($value)
	{
		$this->CutoffTime = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('DispatchCutoffTimePreferencesType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'CutoffTime' =>
					array(
						'required' => false,
						'type' => 'time',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
