<?php
// autogenerated file 05.05.2008 16:30
// $Id: EbatNsCsSetExt_ValidationRuleArrayType.php,v 1.2 2013-04-05 11:15:52 thomasbiniasch Exp $
// $Log: EbatNsCsSetExt_ValidationRuleArrayType.php,v $
// Revision 1.2  2013-04-05 11:15:52  thomasbiniasch
// bugfixes and template updates, first running version milestone!
//
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'EbatNsCsSetExt_ValidationRuleType.php';

/**
 *  
 *
 *
 */
class EbatNsCsSetExt_ValidationRuleArrayType extends EbatNs_ComplexType
{
	/**
	 * @var EbatNsCsSetExt_ValidationRuleType
	 */
	protected $Rule;

	/**
	 * @return EbatNsCsSetExt_ValidationRuleType
	 * @param integer $index 
	 */
	function getRule($index = null)
	{
		if ($index !== null) {
			return $this->Rule[$index];
		} else {
			return $this->Rule;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_ValidationRuleType $value 
	 * @param  $index 
	 */
	function setRule($value, $index = null)
	{
		if ($index !== null) {
			$this->Rule[$index] = $value;
		} else {
			$this->Rule = $value;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_ValidationRuleType $value 
	 */
	function addRule($value)
	{
		$this->Rule[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('EbatNsCsSetExt_ValidationRuleArrayType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
		$this->_elements = array_merge($this->_elements,
			array(
				'Rule' =>
				array(
					'required' => true,
					'type' => 'EbatNsCsSetExt_ValidationRuleType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => true,
					'cardinality' => '1..*'
				)
			));

	}
}
?>
