<?php
// autogenerated file 05.05.2008 16:30
// $Id: EbatNsCsSetExt_AttributeArrayType.php,v 1.2 2013-04-05 11:15:56 thomasbiniasch Exp $
// $Log: EbatNsCsSetExt_AttributeArrayType.php,v $
// Revision 1.2  2013-04-05 11:15:56  thomasbiniasch
// bugfixes and template updates, first running version milestone!
//
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'EbatNsCsSetExt_AttributeType.php';

/**
 *  
 *
 *
 */
class EbatNsCsSetExt_AttributeArrayType extends EbatNs_ComplexType
{
	/**
	 * @var EbatNsCsSetExt_AttributeType
	 */
	protected $Attribute;

	/**
	 * @return EbatNsCsSetExt_AttributeType
	 * @param integer $index 
	 */
	function getAttribute($index = null)
	{
		if ($index !== null) {
			return $this->Attribute[$index];
		} else {
			return $this->Attribute;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_AttributeType $value 
	 * @param  $index 
	 */
	function setAttribute($value, $index = null)
	{
		if ($index !== null) {
			$this->Attribute[$index] = $value;
		} else {
			$this->Attribute = $value;
		}
	}
	/**
	 * @return void
	 * @param EbatNsCsSetExt_AttributeType $value 
	 */
	function addAttribute($value)
	{
		$this->Attribute[] = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('EbatNsCsSetExt_AttributeArrayType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
		$this->_elements = array_merge($this->_elements,
			array(
				'Attribute' =>
				array(
					'required' => true,
					'type' => 'EbatNsCsSetExt_AttributeType',
					'nsURI' => 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd',
					'array' => true,
					'cardinality' => '1..*'
				)
			));

	}
}
?>
