<?php
// autogenerated file 05.05.2008 16:30
// $Id: EbatNsCsSetExt_MessageType.php,v 1.2 2013-04-05 11:15:53 thomasbiniasch Exp $
// $Log: EbatNsCsSetExt_MessageType.php,v $
// Revision 1.2  2013-04-05 11:15:53  thomasbiniasch
// bugfixes and template updates, first running version milestone!
//
//
//
require_once 'EbatNs_ComplexType.php';

/**
 *  
 *
 *
 */
class EbatNsCsSetExt_MessageType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('EbatNsCsSetExt_MessageType', 'http://www.intradesys.com/Schemas/ebay/AttributeData_Extension.xsd');
	$this->_attributes = array_merge($this->_attributes,
		array(
			'color' =>
			array(
				'name' => 'color',
				'type' => 'string',
				'use' => 'required'
			),
			'face' =>
			array(
				'name' => 'face',
				'type' => 'string',
				'use' => 'required'
			),
			'size' =>
			array(
				'name' => 'size',
				'type' => 'string',
				'use' => 'required'
			)
		));

	}
}
?>
