<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated because this type is not used by any call. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/EscrowCodeType.html
 *
 * @property string ByBuyer
 * @property string BySeller
 * @property string None
 * @property string CustomCode
 */
class EscrowCodeType extends EbatNs_FacetType
{
	const CodeType_ByBuyer = 'ByBuyer';
	const CodeType_BySeller = 'BySeller';
	const CodeType_None = 'None';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('EscrowCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_EscrowCodeType = new EscrowCodeType();

?>
