<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated; use <b>SetShippingDiscountProfiles</b> to set Flat 
 * Shipping preferences. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/FlatShippingRateOptionCodeType.html
 *
 * @property string ChargeAmountForEachAdditionalItem
 * @property string DeductAmountFromEachAdditionalItem
 * @property string ShipAdditionalItemsFree
 * @property string CustomCode
 */
class FlatShippingRateOptionCodeType extends EbatNs_FacetType
{
	const CodeType_ChargeAmountForEachAdditionalItem = 'ChargeAmountForEachAdditionalItem';
	const CodeType_DeductAmountFromEachAdditionalItem = 'DeductAmountFromEachAdditionalItem';
	const CodeType_ShipAdditionalItemsFree = 'ShipAdditionalItemsFree';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('FlatShippingRateOptionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_FlatShippingRateOptionCodeType = new FlatShippingRateOptionCodeType();

?>
