<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated because this type is not used by any call. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/LogoTypeCodeType.html
 *
 * @property string WinningBidderNotice
 * @property string Store
 * @property string Custom
 * @property string CustomCode
 */
class LogoTypeCodeType extends EbatNs_FacetType
{
	const CodeType_WinningBidderNotice = 'WinningBidderNotice';
	const CodeType_Store = 'Store';
	const CodeType_Custom = 'Custom';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('LogoTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_LogoTypeCodeType = new LogoTypeCodeType();

?>
