<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated because Cross Promotions are no longer supported in the 
 * APIs. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MerchDisplayCodeType.html
 *
 * @property string DefaultTheme
 * @property string StoreTheme
 * @property string CustomCode
 */
class MerchDisplayCodeType extends EbatNs_FacetType
{
	const CodeType_DefaultTheme = 'DefaultTheme';
	const CodeType_StoreTheme = 'StoreTheme';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MerchDisplayCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MerchDisplayCodeType = new MerchDisplayCodeType();

?>
