<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated because Cross Promotions are no longer supported in the 
 * APIs. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MerchandizingPrefCodeType.html
 *
 * @property string OptIn
 * @property string OptOut
 * @property string CustomCode
 */
class MerchandizingPrefCodeType extends EbatNs_FacetType
{
	const CodeType_OptIn = 'OptIn';
	const CodeType_OptOut = 'OptOut';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MerchandizingPrefCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MerchandizingPrefCodeType = new MerchandizingPrefCodeType();

?>
