<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';
require_once 'AmountType.php';

/**
 * This type specifies the shipping service and cost of the domestic leg of a 
 * Global Shipping Program shipment. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MultiLegShippingServiceType.html
 *
 */
class MultiLegShippingServiceType extends EbatNs_ComplexType
{
	/**
	 * @var token
	 */
	protected $ShippingService;
	/**
	 * @var AmountType
	 */
	protected $TotalShippingCost;

	/**
	 * @return token
	 */
	function getShippingService()
	{
		return $this->ShippingService;
	}
	/**
	 * @return void
	 * @param token $value 
	 */
	function setShippingService($value)
	{
		$this->ShippingService = $value;
	}
	/**
	 * @return AmountType
	 */
	function getTotalShippingCost()
	{
		return $this->TotalShippingCost;
	}
	/**
	 * @return void
	 * @param AmountType $value 
	 */
	function setTotalShippingCost($value)
	{
		$this->TotalShippingCost = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MultiLegShippingServiceType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'ShippingService' =>
					array(
						'required' => false,
						'type' => 'token',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					),
					'TotalShippingCost' =>
					array(
						'required' => false,
						'type' => 'AmountType',
						'nsURI' => 'urn:ebay:apis:eBLBaseComponents',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
