<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * Type defining the <b>ExternalMessageID</b> field used in <b>GetMyMessages</b> to 
 * identify a specific eBay message to retrieve. Up to 10 <b>ExternalMessageID</b> 
 * values can be specified in one API call. The <b>ExternalMessageIDs</b> container 
 * is only available for use on the eBay US site (SiteID 0). 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesExternalMessageIDType.html
 *
 */
class MyMessagesExternalMessageIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesExternalMessageIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesExternalMessageIDType = new MyMessagesExternalMessageIDType();

?>
