<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * This type is deprecated because <b>MyMessagesAlert*</b> are deprecated. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/MyMessagesAlertIDType.html
 *
 */
class MyMessagesAlertIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('MyMessagesAlertIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_MyMessagesAlertIDType = new MyMessagesAlertIDType();

?>
