<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Type defining the possible states of a payment transaction. This type is used by 
 * several containers in order management-related calls. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PaymentTransactionStatusCodeType.html
 *
 * @property string Failed
 * @property string Succeeded
 * @property string Pending
 * @property string CustomCode
 */
class PaymentTransactionStatusCodeType extends EbatNs_FacetType
{
	const CodeType_Failed = 'Failed';
	const CodeType_Succeeded = 'Succeeded';
	const CodeType_Pending = 'Pending';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PaymentTransactionStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PaymentTransactionStatusCodeType = new PaymentTransactionStatusCodeType();

?>
