<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This type is deprecated as Pictures Manager was retired. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/PictureManagerSubscriptionLevelCodeType.html
 *
 * @property string Free
 * @property string Level1
 * @property string Level2
 * @property string Level3
 * @property string Level4
 * @property string CustomCode
 */
class PictureManagerSubscriptionLevelCodeType extends EbatNs_FacetType
{
	const CodeType_Free = 'Free';
	const CodeType_Level1 = 'Level1';
	const CodeType_Level2 = 'Level2';
	const CodeType_Level3 = 'Level3';
	const CodeType_Level4 = 'Level4';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('PictureManagerSubscriptionLevelCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_PictureManagerSubscriptionLevelCodeType = new PictureManagerSubscriptionLevelCodeType();

?>
