<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * No longer applicable to any category. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ProductUseCaseCodeType.html
 *
 * @property string AddItem
 * @property string ReviseItem
 * @property string RelistItem
 * @property string CustomCode
 */
class ProductUseCaseCodeType extends EbatNs_FacetType
{
	const CodeType_AddItem = 'AddItem';
	const CodeType_ReviseItem = 'ReviseItem';
	const CodeType_RelistItem = 'RelistItem';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ProductUseCaseCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ProductUseCaseCodeType = new ProductUseCaseCodeType();

?>
