<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Values indicate whether product creation is enabled, disabled or required for a 
 * category. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ProductCreationEnabledCodeType.html
 *
 * @property string Disabled
 * @property string Enabled
 * @property string Required
 * @property string CustomCode
 */
class ProductCreationEnabledCodeType extends EbatNs_FacetType
{
	const CodeType_Disabled = 'Disabled';
	const CodeType_Enabled = 'Enabled';
	const CodeType_Required = 'Required';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ProductCreationEnabledCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ProductCreationEnabledCodeType = new ProductCreationEnabledCodeType();

?>
