<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that list the possible reasons why a German or Austrian seller's 
 * attemptto distribute a refund to a buyer through the Order Adjustment API's 
 * issueRefund call failed. This type is only applicable to orders subject to the 
 * new eBay payment process on the German and Austrian sites.<br/><br/>Currently, 
 * this type is not applicable since the new eBay payment process for German and 
 * Austrian sites has been put on hold indefinitely. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RefundFailureCodeType.html
 *
 * @property string PaypalBillingAgreementCanceled
 * @property string PaypalRiskDeclinesTransaction
 * @property string CustomCode
 */
class RefundFailureCodeType extends EbatNs_FacetType
{
	const CodeType_PaypalBillingAgreementCanceled = 'PaypalBillingAgreementCanceled';
	const CodeType_PaypalRiskDeclinesTransaction = 'PaypalRiskDeclinesTransaction';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RefundFailureCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundFailureCodeType = new RefundFailureCodeType();

?>
