<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type contains the possible refund, exchange, or store credit 
 * options that aseller may offer a buyer when the buyer wants to return the item. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RefundOptionsCodeType.html
 *
 * @property string MoneyBack
 * @property string Exchange
 * @property string MerchandiseCredit
 * @property string MoneyBackOrExchange
 * @property string MoneyBackOrReplacement
 * @property string CustomCode
 */
class RefundOptionsCodeType extends EbatNs_FacetType
{
	const CodeType_MoneyBack = 'MoneyBack';
	const CodeType_Exchange = 'Exchange';
	const CodeType_MerchandiseCredit = 'MerchandiseCredit';
	const CodeType_MoneyBackOrExchange = 'MoneyBackOrExchange';
	const CodeType_MoneyBackOrReplacement = 'MoneyBackOrReplacement';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RefundOptionsCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundOptionsCodeType = new RefundOptionsCodeType();

?>
