<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * RefundType 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RefundSourceTypeCodeType.html
 *
 * @property string StoreCredit
 * @property string PaymentRefund
 * @property string CustomCode
 */
class RefundSourceTypeCodeType extends EbatNs_FacetType
{
	const CodeType_StoreCredit = 'StoreCredit';
	const CodeType_PaymentRefund = 'PaymentRefund';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RefundSourceTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundSourceTypeCodeType = new RefundSourceTypeCodeType();

?>
