<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type listing the values that indicate whether the refund for the 
 * DE/AT order was applied toward the purchase price, the original shipping price, 
 * or for an additional amount. This type is only applicable for German and 
 * Austrian orders subject to the new eBay payment process. <br/><br/> Currently, 
 * this type is not applicable since the new eBay payment process on the German and 
 * Austrian sites has been put on hold indefinitely. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RefundLineTypeCodeType.html
 *
 * @property string PurchasePrice
 * @property string ShippingPrice
 * @property string Additional
 * @property string CustomCode
 */
class RefundLineTypeCodeType extends EbatNs_FacetType
{
	const CodeType_PurchasePrice = 'PurchasePrice';
	const CodeType_ShippingPrice = 'ShippingPrice';
	const CodeType_Additional = 'Additional';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RefundLineTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RefundLineTypeCodeType = new RefundLineTypeCodeType();

?>
