<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that defines the list of possible actions that a seller cantake 
 * to expedite the release of funds for an order into their account. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/RequiredSellerActionCodeType.html
 *
 * @property string ResolveeBPCase
 * @property string MarkAsShipped
 * @property string ContacteBayCS
 * @property string ResolvePPPIcase
 * @property string SetupPayoutMethod
 * @property string UpdatePayoutMethod
 * @property string None
 * @property string UploadTrackingInfo
 * @property string ResolveBuyerMessageInr
 * @property string ResolveBuyerMessageSnad
 * @property string CustomCode
 * @property string ResolveReturn
 */
class RequiredSellerActionCodeType extends EbatNs_FacetType
{
	const CodeType_ResolveeBPCase = 'ResolveeBPCase';
	const CodeType_MarkAsShipped = 'MarkAsShipped';
	const CodeType_ContacteBayCS = 'ContacteBayCS';
	const CodeType_ResolvePPPIcase = 'ResolvePPPIcase';
	const CodeType_SetupPayoutMethod = 'SetupPayoutMethod';
	const CodeType_UpdatePayoutMethod = 'UpdatePayoutMethod';
	const CodeType_None = 'None';
	const CodeType_UploadTrackingInfo = 'UploadTrackingInfo';
	const CodeType_ResolveBuyerMessageInr = 'ResolveBuyerMessageInr';
	const CodeType_ResolveBuyerMessageSnad = 'ResolveBuyerMessageSnad';
	const CodeType_CustomCode = 'CustomCode';
	const CodeType_ResolveReturn = 'ResolveReturn';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('RequiredSellerActionCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_RequiredSellerActionCodeType = new RequiredSellerActionCodeType();

?>
