<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type contains the list of values that can be used by the seller 
 * to setthe length of time that a Second Chance offer will be available to a 
 * specific bidder towhom the Second Chance offer was presented. The recipient of a 
 * Second Chance offer mustpurchase the Second Chance item within this time or the 
 * offer will expire. Second Chance offers are only applicable for closed auction 
 * listings. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SecondChanceOfferDurationCodeType.html
 *
 * @property string Days_1
 * @property string Days_3
 * @property string Days_5
 * @property string Days_7
 * @property string CustomCode
 */
class SecondChanceOfferDurationCodeType extends EbatNs_FacetType
{
	const CodeType_Days_1 = 'Days_1';
	const CodeType_Days_3 = 'Days_3';
	const CodeType_Days_5 = 'Days_5';
	const CodeType_Days_7 = 'Days_7';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SecondChanceOfferDurationCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SecondChanceOfferDurationCodeType = new SecondChanceOfferDurationCodeType();

?>
