<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type is reserved for future use. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellerPIStatusCodeType.html
 *
 * @property string AcceptedUA
 * @property string MustAcceptUA
 * @property string PIEnabled
 * @property string CustomCode
 */
class SellerPIStatusCodeType extends EbatNs_FacetType
{
	const CodeType_AcceptedUA = 'AcceptedUA';
	const CodeType_MustAcceptUA = 'MustAcceptUA';
	const CodeType_PIEnabled = 'PIEnabled';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellerPIStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellerPIStatusCodeType = new SellerPIStatusCodeType();

?>
