<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Type defining the <b>SellerReturnPreferences</b> container, which consists of 
 * the <b>OptedIn</b> flag that indicates whether or not the seller has opted in to 
 * eBay Managed Returns. <br><br>eBay Managed Returns are currently only available 
 * on the US site; however, eBay Managed Returns will start ramping up for UK 
 * sellers in late September 2013. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellerReturnPreferencesType.html
 *
 */
class SellerReturnPreferencesType extends EbatNs_ComplexType
{
	/**
	 * @var boolean
	 */
	protected $OptedIn;

	/**
	 * @return boolean
	 */
	function getOptedIn()
	{
		return $this->OptedIn;
	}
	/**
	 * @return void
	 * @param boolean $value 
	 */
	function setOptedIn($value)
	{
		$this->OptedIn = $value;
	}
	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellerReturnPreferencesType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__]))
				self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()],
				array(
					'OptedIn' =>
					array(
						'required' => false,
						'type' => 'boolean',
						'nsURI' => 'http://www.w3.org/2001/XMLSchema',
						'array' => false,
						'cardinality' => '0..1'
					)
				));
	}
}
?>
