<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * Enumerated type that indicates whether or not a new DE or AT seller has accepted 
 * thesupplement user agreement related to the new payment process, and if they 
 * have accepted the agreement, whether or not their account is ramped up in the 
 * new payment process. <br/><br/> Currently, this type is not applicable since the 
 * new eBay payment process on the German and Austrian sites has been put on hold 
 * indefinitely. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SellereBayPaymentProcessStatusCodeType.html
 *
 * @property string AcceptedUA
 * @property string MustAcceptUA
 * @property string eBayPaymentProcessEnabled
 * @property string CustomCode
 */
class SellereBayPaymentProcessStatusCodeType extends EbatNs_FacetType
{
	const CodeType_AcceptedUA = 'AcceptedUA';
	const CodeType_MustAcceptUA = 'MustAcceptUA';
	const CodeType_eBayPaymentProcessEnabled = 'eBayPaymentProcessEnabled';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('SellereBayPaymentProcessStatusCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_SellereBayPaymentProcessStatusCodeType = new SellereBayPaymentProcessStatusCodeType();

?>
