<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * A shipping rate scale for shipping through USPS that affects the shipping cost 
 * calculated for USPS (lower if <strong>ShippingRateType</strong> is 
 * <code>DailyPickup</code>). For calculated shipping only. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ShippingRateTypeCodeType.html
 *
 * @property string OnDemand
 * @property string DailyPickup
 * @property string StandardList
 * @property string Counter
 * @property string Discounted
 * @property string CommercialPlus
 * @property string GoldSilver
 * @property string PlatTitanium
 * @property string CustomCode
 */
class ShippingRateTypeCodeType extends EbatNs_FacetType
{
	const CodeType_OnDemand = 'OnDemand';
	const CodeType_DailyPickup = 'DailyPickup';
	const CodeType_StandardList = 'StandardList';
	const CodeType_Counter = 'Counter';
	const CodeType_Discounted = 'Discounted';
	const CodeType_CommercialPlus = 'CommercialPlus';
	const CodeType_GoldSilver = 'GoldSilver';
	const CodeType_PlatTitanium = 'PlatTitanium';
	const CodeType_CustomCode = 'CustomCode';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ShippingRateTypeCodeType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShippingRateTypeCodeType = new ShippingRateTypeCodeType();

?>
