<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_FacetType.php';

/**
 * This enumerated type defines the possible values that can be used in the 
 * <b>ShippingServiceType</b> field of the <b>ShippingServiceCostOverride</b> 
 * container. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/ShippingServiceType.html
 *
 * @property string Domestic
 * @property string International
 */
class ShippingServiceType extends EbatNs_FacetType
{
	const CodeType_Domestic = 'Domestic';
	const CodeType_International = 'International';

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('ShippingServiceType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_ShippingServiceType = new ShippingServiceType();

?>
