<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
//
require_once 'EbatNs_ComplexType.php';

/**
 * Defines the UserConsentRequired feature. If the field is present, the 
 * correspondingfeature applies to the category. The field is returned as an empty 
 * element (i.e., aboolean value is not returned).<br/><br/>Currently, this type is 
 * not applicable since the new eBay payment process on the German and Austrian 
 * sites has been put on hold indefinitely. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/UserConsentRequiredDefinitionType.html
 *
 */
class UserConsentRequiredDefinitionType extends EbatNs_ComplexType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('UserConsentRequiredDefinitionType', 'urn:ebay:apis:eBLBaseComponents');
		if (!isset(self::$_elements[__CLASS__])) {
			self::$_elements[__CLASS__] = array_merge(self::$_elements[get_parent_class()], array());
		}
	}
}
?>
