<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * This is a string wrapper for the eBay ID that uniquely identifies a user. This 
 * is used byseveral other types to identify a specific eBay user, such as 
 * DisputeType.xsd, FeedbackInfoType.xsd, GetAllBidders, OrderType, and so on. 
 * <br><br>For GetAllBidders,some bidder information is anonymous, to protect 
 * bidders from fraud. If the seller makes this API call, the actual IDs of all 
 * bidders on the seller's item will be returned. If a bidder makes this API call, 
 * the bidder's actual ID will be returned, but information for all competing 
 * bidders or outside watchers will be returned as anonymized userIDs. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/UserIDType.html
 *
 */
class UserIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('UserIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_UserIDType = new UserIDType();

?>
