<?php
// autogenerated file 30.09.2013 15:20
// $Id: $
// $Log: $
//
require_once 'EbatNs_SimpleType.php';

/**
 * Specifies a universally unique identifier for an item. This is used to ensure 
 * that you only list a particular item once, particularly if you are listing many 
 * items at once. The identifier can contain only digitsfrom 0-9 and letters from 
 * A-F. The identifier must be 32 characters long. Forexample, 
 * 9CEBD9A6825644EC8D06C436D6CF494B. 
 *
 * @link http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/UUIDType.html
 *
 */
class UUIDType extends EbatNs_SimpleType
{

	/**
	 * @return 
	 */
	function __construct()
	{
		parent::__construct('UUIDType', 'urn:ebay:apis:eBLBaseComponents');

	}
}

$Facet_UUIDType = new UUIDType();

?>
