<?php

namespace InTradeSys\eBay\trading;

/*
 * This class was generated from a WSDL file from March 29, 2023, 11:17 am.
 * Executed by globalsync.
 * Provided and maintained by:
 *
 *  InTradeSys GmbH
 *  Dillenburger Str. 75
 *  D-51105 Cologne
 *  ---
 *  https://www.intradesys.com
 *
 *
 * For paid support options ranging from on-demand,
 * best effort to 24/7 SLAs, please contact us anytime:
 *  ebay.api@InTradeSys.com
 *
 * For more information, visit:
 *  https://sdk.intradesys.com
 */


/**
 * Base response for the
 * LeaveFeedback
 * call. The response includes a
 * FeedbackID
 * value, which is automatically generated by eBay if the caller is successfully at submitting the Feedback entry.
 **/
class LeaveFeedbackResponseType extends EbatNs_Response
{
    const TAG = 'LeaveFeedbackResponseType';
    const NAME = 'LeaveFeedbackResponseType';
    const XMLNS = 'urn:ebay:apis:eBLBaseComponents';

    /**
     * @var string|null
     */
    protected $FeedbackID = null;


    /**
     * @return string|null|mixed Depending on the assigned data converter: mixed
     */
    public function getFeedbackID()
    {
        return $this->_dc($this->FeedbackID, 'FeedbackID');
    }

    /**
     * @param string|null $value
     * @return void
     */
    public function setFeedbackID($value)
    {
        $this->FeedbackID = self::_string($value);
    }
    
    /**
     * Register child elements and attributes
     */
    public static function _register()
    {
        self::assignElements(['FeedbackID' => []], parent::NAME);
        self::assignAttributes([]);
    }

}

LeaveFeedbackResponseType::_register();
